/*
 * Slack Web API
 *
 * One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.
 *
 * The version of the OpenAPI document: 1.7.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Blocks : This is a very loose definition, in the future, we'll populate this with deeper schema in this definition namespace.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Blocks {
}

impl Blocks {
    /// This is a very loose definition, in the future, we'll populate this with deeper schema in this definition namespace.
    pub fn new() -> Blocks {
        Blocks {
        }
    }
}


